// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:MolecularWeightCalculator.CapillaryFlow.ComputeMeCNViscosity(System.Double,System.Double,MolecularWeightCalculator.UnitOfTemperature,MolecularWeightCalculator.UnitOfViscosity)~System.Double")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:MolecularWeightCalculator.CapillaryFlow.ConvertTemperature(System.Double,MolecularWeightCalculator.UnitOfTemperature,MolecularWeightCalculator.UnitOfTemperature)~System.Double")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:MolecularWeightCalculator.Formula.ElementAndMassTools.ComputeIsotopicAbundances(System.String@,System.Int16,System.String@,System.Double[,]@,System.Int32@,System.Boolean,System.String,System.String,System.String,System.String,System.Boolean)~System.Int16")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:MolecularWeightCalculator.Formula.ElementAndMassTools.ConvertStickDataToGaussian2DArray(System.Collections.Generic.List{System.Collections.Generic.KeyValuePair{System.Double,System.Double}},System.Int32,System.Double,System.Int32)~System.Collections.Generic.List{System.Collections.Generic.KeyValuePair{System.Double,System.Double}}")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:MolecularWeightCalculator.Formula.ElementAndMassTools.ConvoluteMass(System.Double,System.Int16,System.Int16,System.Double)~System.Double")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:MolecularWeightCalculator.Formula.ElementAndMassTools.FindIndexForNominalMass(System.Int32[,],System.Int32,System.Int16,System.Int32,System.Collections.Generic.IReadOnlyList{MolecularWeightCalculator.Formula.IsotopeInfo})~System.Int32")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:MolecularWeightCalculator.Formula.FormulaParser.ComputeFormulaMass(MolecularWeightCalculator.Formula.FormulaParseData)")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:MolecularWeightCalculator.Formula.FormulaParser.ComputePercentComposition(MolecularWeightCalculator.Formula.ComputationStats)")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:MolecularWeightCalculator.Formula.FormulaParser.DetermineTotalElementCounts(MolecularWeightCalculator.Formula.FormulaParseData,MolecularWeightCalculator.Formula.FormulaData,MolecularWeightCalculator.Formula.FormulaComponentGroup,System.Int32,System.Double)")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:MolecularWeightCalculator.Formula.FormulaParser.ParseFormulaComponents(System.String,MolecularWeightCalculator.Formula.FormulaParseData,System.Double,MolecularWeightCalculator.Formula.FormulaComponentGroup,System.Int32,System.Int32)")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:MolecularWeightCalculator.Formula.FormulaParser.ParseNumberAtStart(System.String,System.Int32@,MolecularWeightCalculator.Formula.ErrorDetails,System.Int32,System.Boolean)~System.Double")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:MolecularWeightCalculator.FormulaFinder.FormulaSearcher.ComputeSortKey(System.Text.StringBuilder,System.String)~System.String")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:MolecularWeightCalculator.FormulaFinder.FormulaSearcher.ConstructAndVerifyCompoundWork(MolecularWeightCalculator.FormulaFinder.SearchOptions,System.Text.StringBuilder,System.Double,System.Double,System.Double,System.Double,System.Int32,System.Collections.Generic.Dictionary{System.String,System.Int32},System.Double@)~System.Boolean")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:MolecularWeightCalculator.FormulaFinder.FormulaSearcher.CorrectChargeEmpirical(MolecularWeightCalculator.FormulaFinder.SearchOptions,System.Double,MolecularWeightCalculator.FormulaFinder.FormulaSearcher.ElementNum,System.Boolean@)~System.Double")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:MolecularWeightCalculator.FormulaFinder.FormulaSearcher.GetSearchResult(MolecularWeightCalculator.FormulaFinder.SearchOptions,System.Boolean,System.Text.StringBuilder,System.Double,System.Double,System.Double,System.Collections.Generic.Dictionary{System.String,System.Int32})~MolecularWeightCalculator.FormulaFinder.SearchResult")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:MolecularWeightCalculator.FormulaFinder.FormulaSearcher.OldFormulaFinder(MolecularWeightCalculator.FormulaFinder.SearchOptions,System.Boolean,MolecularWeightCalculator.FormulaFinder.FormulaSearcher.CalculationMode,System.Collections.Generic.IList{MolecularWeightCalculator.FormulaFinder.CandidateElement},System.Double,System.Double,System.Double)~System.Collections.Generic.List{MolecularWeightCalculator.FormulaFinder.SearchResult}")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:MolecularWeightCalculator.Sequence.Peptide.CheckSequenceAgainstCleavageRule(System.String,System.String,System.String,System.Boolean,System.Int16@,System.String,System.String,System.Boolean)~System.Boolean")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:MolecularWeightCalculator.Sequence.Peptide.GetFragmentationMasses~System.Collections.Generic.List{MolecularWeightCalculator.Sequence.FragmentationSpectrumData}")]
[assembly: SuppressMessage("Redundancy", "RCS1163:Unused parameter.", Justification = "Leave for readability", Scope = "member", Target = "~M:MolecularWeightCalculator.Formula.ElementsAndAbbrevs.MemoryLoadElements(MolecularWeightCalculator.Formula.ElementMassMode,System.Int16,MolecularWeightCalculator.ElementStatsType)")]
[assembly: SuppressMessage("Usage", "RCS1246:Use element access.", Justification = "Prefer to use .First()", Scope = "member", Target = "~M:MolecularWeightCalculator.Formula.ElementAndMassTools.ConvertStickDataToGaussian2DArray(System.Collections.Generic.List{System.Collections.Generic.KeyValuePair{System.Double,System.Double}},System.Int32,System.Double,System.Int32)~System.Collections.Generic.List{System.Collections.Generic.KeyValuePair{System.Double,System.Double}}")]
[assembly: SuppressMessage("Usage", "RCS1246:Use element access.", Justification = "Prefer to use .First()", Scope = "member", Target = "~M:MolecularWeightCalculator.Formula.FormulaParser.ComputeFormulaMass(MolecularWeightCalculator.Formula.FormulaParseData)")]
[assembly: SuppressMessage("Usage", "RCS1246:Use element access.", Justification = "Prefer to use .First()", Scope = "member", Target = "~M:MolecularWeightCalculator.Formula.FormulaParser.DetermineTotalElementCounts(MolecularWeightCalculator.Formula.FormulaParseData,MolecularWeightCalculator.Formula.FormulaData,MolecularWeightCalculator.Formula.FormulaComponentGroup,System.Int32,System.Double)")]
[assembly: SuppressMessage("Usage", "RCS1246:Use element access.", Justification = "Prefer to use .First()", Scope = "member", Target = "~P:MolecularWeightCalculator.Formula.FormulaParseData.Components")]
[assembly: SuppressMessage("Usage", "RCS1246:Use element access.", Justification = "Prefer to use .First()", Scope = "member", Target = "~P:MolecularWeightCalculator.Formula.FormulaParseData.Stats")]
