// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~M:MwtWinDllTest.frmMwtWinDllTest.cboStdDevMode_SelectedIndexChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~M:MwtWinDllTest.frmMwtWinDllTest.cboWeightMode_SelectedIndexChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmMwtWinDllTest.cboFormulaFinderTestMode")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmMwtWinDllTest.cboStdDevMode")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmMwtWinDllTest.cboWeightMode")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~M:MwtWinDllTest.frmMwtWinDllTest.chkShowRTFSource_CheckedChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmMwtWinDllTest.chkShowRTFSource")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~M:MwtWinDllTest.frmMwtWinDllTest.cmdClose_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~M:MwtWinDllTest.frmMwtWinDllTest.cmdConvertToEmpirical_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~M:MwtWinDllTest.frmMwtWinDllTest.cmdExpandAbbreviations_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~M:MwtWinDllTest.frmMwtWinDllTest.cmdFindMass_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~M:MwtWinDllTest.frmMwtWinDllTest.cmdTestFormulaFinder_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~M:MwtWinDllTest.frmMwtWinDllTest.cmdTestFunctions_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~M:MwtWinDllTest.frmMwtWinDllTest.cmdTestGetTrypticName_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmMwtWinDllTest.cmdClose")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmMwtWinDllTest.cmdConvertToEmpirical")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmMwtWinDllTest.cmdExpandAbbreviations")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmMwtWinDllTest.cmdFindMass")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmMwtWinDllTest.cmdTestFormulaFinder")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmMwtWinDllTest.cmdTestFunctions")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmMwtWinDllTest.cmdTestGetTrypticName")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmMwtWinDllTest.lblDLLVersion")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmMwtWinDllTest.lblFormula")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmMwtWinDllTest.lblMass")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmMwtWinDllTest.lblMassAndStdDev")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmMwtWinDllTest.lblMassAndStdDevLabel")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmMwtWinDllTest.lblMassLabel")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmMwtWinDllTest.lblProgress")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmMwtWinDllTest.lblStatus")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmMwtWinDllTest.lblStatusLabel")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmMwtWinDllTest.lblStdDevMode")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmMwtWinDllTest.lblWeightMode")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~M:MwtWinDllTest.frmTextbrowser.mnuEditCopy_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~M:MwtWinDllTest.frmTextbrowser.mnuEditCut_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~M:MwtWinDllTest.frmTextbrowser.mnuEditFontSizeDecrease_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~M:MwtWinDllTest.frmTextbrowser.mnuEditFontSizeIncrease_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~M:MwtWinDllTest.frmTextbrowser.mnuEditPaste_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~M:MwtWinDllTest.frmTextbrowser.mnuFileExit_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmTextbrowser.mnuEdit")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmTextbrowser.mnuEditCopy")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmTextbrowser.mnuEditCut")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmTextbrowser.mnuEditFontSizeDecrease")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmTextbrowser.mnuEditFontSizeIncrease")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmTextbrowser.mnuEditPaste")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmTextbrowser.mnuEditSep1")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmTextbrowser.mnuFile")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmTextbrowser.mnuFileExit")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmMwtWinDllTest.txtFormula")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmMwtWinDllTest.txtRTFSource")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "member", Target = "~P:MwtWinDllTest.frmTextbrowser.txtData")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "type", Target = "~T:MwtWinDllTest.frmMwtWinDllTest")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Allowed name", Scope = "type", Target = "~T:MwtWinDllTest.frmTextbrowser")]
