version: 1.0.{build}
image: Visual Studio 2019
before_build:
- cmd: nuget.exe restore MolecularWeightCalculator.sln
build:
  project: MolecularWeightCalculator.sln
  verbosity: minimal
artifacts:
- path: bin\Release\MolecularWeightCalculator.dll
