# Jekyll configuration
name: Molecular-Weight-Calculator-DLL
description: .NET DLL version of the Molecular Weight Calculator, supporting a range of molecular weight calculations for both chemical formulas and amino acids.
url: https://pnnl-comp-mass-spec.github.io/Molecular-Weight-Calculator-DLL/
